#
# Makefile for cclogic device.
#

obj-$(CONFIG_CCLOGIC)		    += cclogic-core.o
obj-$(CONFIG_CCLOGIC)               += cclogic-class.o
obj-$(CONFIG_CCLOGIC)           += cclogic-letv.o
obj-$(CONFIG_TYPEC_CCLOGIC_TUSB320HAI) += tusb320hai.o
obj-$(CONFIG_TYPEC_CCLOGIC_PI5USBD)  += pi5usb30216d.o


#Added
obj-$(CONFIG_USB_CCLOGIC_PI5USB)	+= pi5usb30216a.o
obj-$(CONFIG_USB_CCLOGIC_TUSB302L)	+= tusb302l.o
obj-$(CONFIG_USB_CCLOGIC_PTN5150)	+= ptn5150.o
obj-$(CONFIG_USB_CCLOGIC_PER30216)	+= pericom_i2c_30216c_v1.o
obj-$(CONFIG_USB_CCLOGIC_TUSB320)	+= tusb320.o
